# Generated by Django 6.0.4 on 2026-04-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_category_coursemenu_galleryimage_sitesettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
