# Generated by Django 6.0.4 on 2026-04-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_menuitem_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('reservation', 'ご予約について / About Reservations'), ('menu', 'メニューについて / About Menu'), ('course', 'コース料理について / About Course Meals'), ('private', '個室・貸切について / Private Rooms & Events'), ('allergy', 'アレルギー・食事制限について / Allergies & Dietary Restrictions'), ('career', '採用について / Careers'), ('press', '取材・メディアについて / Press & Media'), ('other', 'その他 / Other')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
