# Generated by Django 6.0.4 on 2026-04-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_contactsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemenu',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
