# Generated by GitHub Copilot
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_coursemenu_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(default='03-1234-5678', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_hours_ja',
            field=models.CharField(default='月〜土 10:00〜20:00', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_hours_en',
            field=models.CharField(default='Mon–Sat 10:00–20:00', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_note_ja',
            field=models.CharField(default='日曜・祝日は除く', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_note_en',
            field=models.CharField(default='(Closed Sundays & holidays)', max_length=120),
        ),
    ]
